/* ============================================================
   PROYECTO  : Northwind
   ARCHIVO   : power_query_completo.txt
   FECHA     : 2026-03-07
   VERSION   : 1.1
   DESC      : Código M completo del modelo Power BI.
               Contiene parámetros, conexión base, dimensiones
               (incluida DimDate generada en PQ) y tabla de hechos
               conectados a SQL Server.

   ESTRUCTURA:
     1. Parámetros     → PRMServidor, PRMBaseDatos
     2. Conexión base  → CNXSqlServer         [Enable Load = OFF]
     3. Dimensiones    → DimCategory, DimCustomer, DimProduct, DimDate
     4. Hechos         → FactSales

   CONVENCIÓN DE NOMBRES DE STEPS:
     Source       → conexión o referencia al query origen
     Navegacion   → acceso a la vista específica en SQL Server
     ColumnasSel  → selección de columnas (solo en Fact)

   CHANGELOG:
     v1.0 - 2026-03-07 - Creación inicial
     v1.1 - 2026-03-07 - Renombrar queries eliminando guiones bajos
                         Agregar DimDate generada en Power Query
   ============================================================ */


/* ------------------------------------------------------------
   SECCIÓN 1: PARÁMETROS

   Centraliza la configuración de entorno.
   Si el servidor o base de datos cambia, solo se modifica aquí.
   Afecta automáticamente todas las queries que usan CNXSqlServer.
   ------------------------------------------------------------ */

// QUERY        : PRMServidor
// TIPO         : Parámetro de texto
// DESC         : Nombre o IP del servidor SQL Server
// ENABLE LOAD  : No (parámetro)
// CARPETA PQ   : _Parametros
"localhost" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]


// QUERY        : PRMBaseDatos
// TIPO         : Parámetro de texto
// DESC         : Nombre de la base de datos origen
// ENABLE LOAD  : No (parámetro)
// CARPETA PQ   : _Parametros
"Northwind" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]


/* ------------------------------------------------------------
   SECCIÓN 2: CONEXIÓN BASE

   Query raíz reutilizado por todas las dimensiones y hechos.
   IMPORTANTE: Enable Load debe estar en OFF para que no genere
   una tabla vacía en el modelo semántico.
   ------------------------------------------------------------ */

// QUERY        : CNXSqlServer
// TIPO         : Conexión base
// DESC         : Conexión raíz a SQL Server usando los parámetros
//                PRMServidor y PRMBaseDatos. Todas las demás
//                queries la referencian como punto de entrada.
// ENABLE LOAD  : NO — desactivar en Power Query Editor
// CARPETA PQ   : _Conexiones
// CHANGELOG    :
//   v1.0 - 2026-03-07 - Creación inicial
let
    Source = Sql.Database(PRMServidor, PRMBaseDatos)
in
    Source


/* ------------------------------------------------------------
   SECCIÓN 3: DIMENSIONES

   Cada query referencia CNXSqlServer como origen, excepto
   DimDate que se genera completamente en Power Query a partir
   del rango de fechas de FactSales.
   No contienen lógica de negocio — esa responsabilidad
   pertenece a las vistas en SQL Server.
   ------------------------------------------------------------ */

// QUERY        : DimCategory
// TIPO         : Tabla dimensión
// DESC         : Dimensión de categorías de productos.
// ORIGEN SQL   : dbo.vw_DimCategory
// ENABLE LOAD  : Sí
// CARPETA PQ   : Dimensiones
// CHANGELOG    :
//   v1.0 - 2026-03-07 - Creación inicial
let
    Source     = CNXSqlServer,
    Navegacion = Source{[Schema="dbo", Item="vw_DimCategory"]}[Data]
in
    Navegacion


// QUERY        : DimCustomer
// TIPO         : Tabla dimensión
// DESC         : Dimensión de clientes.
// ORIGEN SQL   : dbo.vw_DimCustomer
// ENABLE LOAD  : Sí
// CARPETA PQ   : Dimensiones
// CHANGELOG    :
//   v1.0 - 2026-03-07 - Creación inicial
let
    Source     = CNXSqlServer,
    Navegacion = Source{[Schema="dbo", Item="vw_DimCustomer"]}[Data]
in
    Navegacion


// QUERY        : DimProduct
// TIPO         : Tabla dimensión
// DESC         : Dimensión de productos con su categoría asociada.
// ORIGEN SQL   : dbo.vw_DimProduct
// ENABLE LOAD  : Sí
// CARPETA PQ   : Dimensiones
// CHANGELOG    :
//   v1.0 - 2026-03-07 - Creación inicial
let
    Source     = CNXSqlServer,
    Navegacion = Source{[Schema="dbo", Item="vw_DimProduct"]}[Data]
in
    Navegacion


// QUERY        : DimDate
// TIPO         : Tabla dimensión — generada en Power Query
// DESC         : Dimensión de tiempo construida dinámicamente
//                a partir del rango de fechas de FactSales.
//                No se importa desde SQL Server.
// ORIGEN       : Generada en Power Query — referencia FactSales[OrderDate]
// ENABLE LOAD  : Sí
// CARPETA PQ   : Dimensiones
// COLUMNAS     : Date, Year, Month, Month Name, Quarter,
//                Quarter Name, Day of Week, Day Name
// NOTAS        : El rango se recalcula automáticamente en cada
//                refresh tomando MIN y MAX de FactSales[OrderDate].
//                No hay fechas hardcodeadas.
// CHANGELOG    :
//   v1.1 - 2026-03-07 - Creación inicial
let
    Source                   = {(Number.From(List.Min(FactSales[OrderDate])))..(Number.From(List.Max(FactSales[OrderDate])))},
    #"Converted to Table"    = Table.FromList(Source, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
    #"Changed Type"          = Table.TransformColumnTypes(#"Converted to Table",{{"Date", type date}}),
    #"Inserted Year"         = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Month"        = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Month Name"   = Table.AddColumn(#"Inserted Month", "Month Name", each Text.Start(Date.MonthName([Date]), 3), type text),
    #"Inserted Quarter"      = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    #"Inserted Quarter Name" = Table.AddColumn(#"Inserted Quarter", "Quarter Name", each Text.Combine({"Q", Text.From([Quarter], "en-US")}), type text),
    #"Inserted Day of Week"  = Table.AddColumn(#"Inserted Quarter Name", "Day of Week", each Date.DayOfWeek([Date]), Int64.Type),
    #"Inserted Day Name"     = Table.AddColumn(#"Inserted Day of Week", "Day Name", each Text.Start(Date.DayOfWeekName([Date]), 3), type text)
in
    #"Inserted Day Name"


/* ------------------------------------------------------------
   SECCIÓN 4: HECHOS

   Tablas de mayor volumen — siempre al final del refresh.
   Se aplica selección explícita de columnas para evitar
   cargar campos innecesarios al modelo y reducir el tamaño
   del dataset.
   ------------------------------------------------------------ */

// QUERY        : FactSales
// TIPO         : Tabla de hechos
// DESC         : Tabla de hechos de ventas con métricas de
//                cantidad y revenue neto por orden, cliente,
//                producto y categoría.
// ORIGEN SQL   : dbo.vw_FactSales
// ENABLE LOAD  : Sí
// CARPETA PQ   : Hechos
// COLUMNAS     : OrderID, CustomerID, ProductID, CategoryID,
//                OrderDate, Quantity, NetRevenue
// NOTAS        : Se usa SelectColumns para cargar solo las
//                columnas necesarias al modelo. Si se agregan
//                métricas nuevas a la vista SQL, incluirlas
//                también en el paso ColumnasSel.
//                DimDate referencia esta tabla para calcular
//                su rango de fechas dinámicamente.
// CHANGELOG    :
//   v1.0 - 2026-03-07 - Creación inicial
let
    Source      = CNXSqlServer,
    Navegacion  = Source{[Schema="dbo", Item="vw_FactSales"]}[Data],
    ColumnasSel = Table.SelectColumns(Navegacion, {
                      "OrderID",
                      "CustomerID",
                      "ProductID",
                      "CategoryID",
                      "OrderDate",
                      "Quantity",
                      "NetRevenue"
                  })
in
    ColumnasSel
